[package]
name = "timekpr-dbus-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
dbus-tokio = "0.7"
dbus = "0.9"
