[package]
name = "timekpr-dbus-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
async-nats = "0.46"
dbus-tokio = "0.7"
dbus = "0.9"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
